# Generated by Django 3.2.6 on 2021-08-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Cashier', 'Cashier'), ('Manager', 'Manager'), ('Accountant', 'Accountant')], max_length=100, null=True),
        ),
    ]
