# Generated by Django 3.2.6 on 2021-08-19 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Stationaries', 'Stationaries'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Wears', 'Wears'), ('Fees', 'Fees'), ('Drug', 'Drug'), ('Fittings', 'Fittings')], max_length=100, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Income Sources',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Stationaries', 'Stationaries'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Wears', 'Wears'), ('Fees', 'Fees'), ('Drug', 'Drug'), ('Fittings', 'Fittings')], max_length=100, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
