# Generated by Django 3.2.6 on 2021-08-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_income_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='Remarks',
            new_name='remarks',
        ),
    ]
