# Generated by Django 3.2.6 on 2021-08-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_remarks_income_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(choices=[('Stationaries', 'Stationaries'), ('Food', 'Food'), ('Wears', 'Wears'), ('Airtime', 'Airtime'), ('Airtime', 'Airtime'), ('Fees', 'Fees'), ('Drug', 'Drug'), ('Fittings', 'Fittings'), ('Salary', 'Salary'), ('Fuel', 'Fuel'), ('Paper', 'Paper'), ('Engine Oil', 'Engine Oil'), ('Repairs', 'Repairs')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Photocopy', 'Photocopy'), ('Typing', 'Typing'), ('Printing', 'Printing'), ('Passport', 'Passport'), ('Email', 'Email'), ('Application', 'Application'), ('Result', 'Result'), ('Laminating', 'Laminating'), ('Sell of Agreement Form', 'Sale of Agreement Form'), ('Sell of Evelope', 'Sell of Evelope'), ('Graphics Design', 'Graphics Designe')], max_length=100, null=True),
        ),
    ]
