# Generated by Django 3.2.6 on 2021-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210823_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(choices=[('Stationaries', 'Stationaries'), ('Family Up Keep', 'Family Up Keep'), ('Airtime Recharge', 'Airtime Recharge'), ('Repairs', 'Repairs'), ('Staff Salary', 'Staff Salary'), ('Maintainance', 'Maintainance')], max_length=100, null=True),
        ),
    ]
